version: "3"
services:
  web_app:
    build: .
    environment:
      - HOST=0.0.0.0
      - PORT=8080
    ports:
      - 8080:8080
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - 80:80
    volumes:
      - ./app/web_app_nginx.conf:/etc/nginx/nginx.conf
    links:
      - web_app

volumes:
  app:
